COLUMN_SEMANTICS = {
    "tbl_aces": {
        "app_index": "Unique auto-increment identifier for each ACES application row",
        "sku_temp": "Temporary SKU associated with this application row",
        "aces_file_name": "Name of the ACES source file this row was imported from",
        "product_line": "Product line identifier for the associated part",
        "vehicle_type": "Vehicle classification such as car, truck, SUV, etc",
        "year_start": "Starting model year this application applies to",
        "year_end": "Ending model year this application applies to",
        "make": "Vehicle make name",
        "make_aces_id": "ACES identifier for the vehicle make",
        "model": "Vehicle model name",
        "model_aces_id": "ACES identifier for the vehicle model",
        "submodel": "Vehicle submodel or trim",
        "submodel_aces_id": "ACES identifier for the vehicle submodel",
        "engine": "Full engine description for the application",
        "engine_aces_id": "ACES identifier for the engine",
        "engine_designation": "Engine designation code used by ACES",
        "engine_designation_aces_id": "ACES identifier for engine designation",
        "engine_vin": "Engine VIN code used to distinguish engine variants",
        "engine_vin_aces_id": "ACES identifier for engine VIN",
        "engine_version": "Engine version descriptor",
        "engine_version_aces_id": "ACES identifier for engine version",
        "engine_reduced": "Simplified engine description used for titles and notes",
        "engine_mfr": "Engine manufacturer name",
        "engine_mfr_aces_id": "ACES identifier for engine manufacturer",
        "aspiration": "Aspiration type such as naturally aspirated, turbocharged, or supercharged",
        "aspiration_aces_id": "ACES identifier for aspiration type",
        "cylinder_head_type": "Cylinder head configuration",
        "cylinder_head_type_aces_id": "ACES identifier for cylinder head type",
        "valves_per_engine": "Number of valves in the engine",
        "valves_per_engine_aces_id": "ACES identifier for valves per engine",
        "fuel_type": "Type of fuel used by the engine",
        "fuel_type_aces_id": "ACES identifier for fuel type",
        "fuel_delivery_type": "Fuel delivery method",
        "fuel_delivery_type_aces_id": "ACES identifier for fuel delivery type",
        "fuel_delivery_subtype": "Fuel delivery subtype detail",
        "fuel_delivery_subtype_aces_id": "ACES identifier for fuel delivery subtype",
        "fuel_system_design": "Fuel system design classification",
        "fuel_system_design_aces_id": "ACES identifier for fuel system design",
        "fuel_system_control_type": "Fuel system control type",
        "fuel_system_control_type_aces_id": "ACES identifier for fuel system control type",
        "body_type": "Vehicle body style",
        "body_type_aces_id": "ACES identifier for body style",
        "body_num_doors": "Number of doors on the vehicle body",
        "body_num_doors_aces_id": "ACES identifier for number of doors",
        "mfr_body_code": "Manufacturer body code",
        "mfr_body_code_aces_id": "ACES identifier for manufacturer body code",
        "bed_type": "Truck bed type",
        "bed_type_aces_id": "ACES identifier for bed type",
        "bed_length": "Truck bed length",
        "bed_length_aces_id": "ACES identifier for bed length",
        "wheel_base": "Wheelbase measurement",
        "wheel_base_aces_id": "ACES identifier for wheelbase",
        "drive_type": "Drive configuration such as FWD, RWD, AWD, or 4WD",
        "drive_type_aces_id": "ACES identifier for drive type",
        "transmission_type": "Transmission type such as automatic or manual",
        "transmission_type_aces_id": "ACES identifier for transmission type",
        "transmission_mfr": "Transmission manufacturer",
        "transmission_mfr_aces_id": "ACES identifier for transmission manufacturer",
        "transmission_mfr_code": "Transmission manufacturer code",
        "transmission_mfr_code_aces_id": "ACES identifier for transmission manufacturer code",
        "transmission_control_type": "Transmission control type",
        "transmission_control_type_aces_id": "ACES identifier for transmission control type",
        "transmission_num_speeds": "Number of transmission speeds",
        "transmission_num_speeds_aces_id": "ACES identifier for number of transmission speeds",
        "brake_system": "Brake system configuration",
        "brake_system_aces_id": "ACES identifier for brake system",
        "brake_abs": "ABS configuration",
        "brake_abs_aces_id": "ACES identifier for ABS",
        "front_brake_type": "Front brake type",
        "front_brake_type_aces_id": "ACES identifier for front brake type",
        "rear_brake_type": "Rear brake type",
        "rear_brake_type_aces_id": "ACES identifier for rear brake type",
        "steering_system": "Steering system type",
        "steering_system_aces_id": "ACES identifier for steering system",
        "steering_type": "Steering type",
        "steering_type_aces_id": "ACES identifier for steering type",
        "front_spring_type": "Front suspension spring type",
        "front_spring_type_aces_id": "ACES identifier for front spring type",
        "rear_spring_type": "Rear suspension spring type",
        "rear_spring_type_aces_id": "ACES identifier for rear spring type",
        "aces_notes": "Raw ACES notes provided in the source data",
        "part_type": "Part type or category associated with this application",
        "part_type_aces_id": "ACES identifier for the part type",
        "part1": "Part identifier associated with this application",
        "part1_quantity": "Quantity of part1 required for this application",
        "year_range": "Preformatted year range string used for listings",
        "combined_notes": "Processed notes combined for listing display",
        "ebay_vehicle_compatibility": "Prebuilt eBay vehicle compatibility description",
        "ca_group_enabled": "Flag indicating this row participates in a compatibility aggregation group",
        "ca_group_key": "Key used to group similar applications for compatibility aggregation",
        "ca_group_number": "Identifier for the compatibility aggregation group",
        "ca_group_ebay_vehicle_compatibility_valid": "Flag indicating if grouped eBay compatibility text is valid",
        "base_vehicle_aces_id": "ACES BaseVehicle identifier reference",
    },
    "tbl_pies": {
        "part_index": "Unique auto-increment identifier for each PIES part row",
        "pies_file_name": "Name of the PIES source file this part was imported from",
        "product_line": "Product line or series the part belongs to",
        "indiv_number": "Individual item number within the PIES file",
        "part_sku": "SKU assigned to the part for internal or listing use",
        "part_enabled": "Flag indicating if the part is active and should be used in listings",
        "indiv_enabled": "Flag indicating if this specific individual item record is active",
        "part_number": "Manufacturer part number for the item",
        "epid": "eBay Product ID associated with the part",
        "asin": "Amazon Standard Identification Number associated with the part",
        "upc": "Universal Product Code for the part",
        "part_type": "Type or category of the part",
        "part_terminology_id": "Identifier for the standardized part terminology",
        "brand_aaia_id": "AAIA identifier for the part brand",
        "subbrand_aaia_id": "AAIA identifier for the part sub-brand",
        "description_short": "Short marketing description of the part",
        "description_long": "Detailed description of the part for listings and documentation",
        "quantity_of_each_ea": "Quantity of the part included per each unit",
        "attribute": "Collection of PIES attributes describing the part features",
        "oem_mfg": "Original equipment manufacturer name",
        "oem_pn": "Original equipment manufacturer part number",
        "aftermarket_mfg": "Aftermarket manufacturer name",
        "aftermarket_pn": "Aftermarket manufacturer part number",
        "item_length_in": "Physical length of the part in inches",
        "item_width_in": "Physical width of the part in inches",
        "item_height_in": "Physical height of the part in inches",
        "item_weight_lbs": "Physical weight of the part in pounds",
        "image_name": "Primary image file name used for the part listing",
        "image2_name": "Secondary image file name for additional views",
        "image3_name": "Tertiary image file name for additional views",
        "image4_name": "Quaternary image file name for additional views",
        "search_col": "Computed searchable column concatenating key text fields to support fast text search",
    },
    "tbl_auto_part_listing": {
        "listing_category_name": "The category of the listing",
        "pies_file_name": "Name of the PIES file the listing data is derived from",
        "group_key": "Unique identifier tying multiple listings together as one logical compatibility group",
        "ebay_sku": "SKU used for the eBay listing",
        "amazon_sku": "SKU used for the Amazon listing",
        "year_range_title": "Vehicle year or year range displayed in the listing title",
        "make_title": "Vehicle make displayed in the listing title",
        "model_title": "Vehicle model displayed in the listing title",
        "combined_notes_title": "Combined compatibility notes displayed in the listing title",
        "position_title": "Vehicle position shown in the listing title such as Front, Rear, Left, or Right",
        "compatibility_table": "Flag indicating if a compatibility table should be generated for the listing",
        "ebay_vehicle_compatibility": "Flag indicating if eBay vehicle compatibility data should be included",
        "amazon_vehicle_compatibility": "Flag indicating if Amazon vehicle compatibility data should be included",
        "part_type": "General type or category of the part used in the listing",
        "part_terminology_id": "Standardized part terminology identifier",
        "part1": "Primary part identifier associated with this listing",
        "part1_quantity": "Quantity of part1 included in the listing",
        "part1_supplier_pn": "Supplier part number for part1",
        "part1_part_sku": "Internal SKU for part1",
        "part1_enabled": "Flag indicating if part1 is active and should be used in the listing",
        "part1_epid": "eBay Product ID for part1",
        "part1_asin": "Amazon ASIN for part1",
        "part1_upc": "UPC code for part1",
        "part1_brand_aaia_id": "Brand AAIA identifier for part1",
        "part1_subbrand_aaia_id": "Sub-brand AAIA identifier for part1",
        "part1_oem_mfg": "OEM manufacturer name for part1",
        "part1_oem_pn": "OEM part number for part1",
        "part1_aftermarket_mfg": "Aftermarket manufacturer name for part1",
        "part1_aftermarket_pn": "Aftermarket part number for part1",
        "part1_description": "Description of part1 used in the listing",
        "part1_part_type": "Specific part type or category for part1",
        "part1_attribute": "Attribute data describing features of part1",
        "part1_item_length_in": "Physical length of part1 in inches",
        "part1_item_width_in": "Physical width of part1 in inches",
        "part1_item_height_in": "Physical height of part1 in inches",
        "part1_item_weight_lbs": "Physical weight of part1 in pounds",
    },
    "tbl_auto_app_listing": {
        "listing_category_name": "The category of the listing",
        "aces_file_name": "Name of the ACES file the application data was derived from",
        "pies_file_name": "Name of the PIES file the listing details were derived from",
        "group_key": "Unique identifier tying multiple listings together as one logical compatibility group",
        "ebay_sku": "SKU used for the eBay listing",
        "amazon_sku": "SKU used for the Amazon listing",
        "year_range_title": "Vehicle year or year range displayed in the listing title",
        "make_title": "Vehicle make displayed in the listing title",
        "model_title": "Vehicle model displayed in the listing title",
        "model_magento": "Vehicle model formatting used specifically for Magento or website display",
        "combined_notes_title": "Combined compatibility notes displayed in the listing title",
        "position_title": "Vehicle position shown in the listing title such as Front, Rear, Left, or Right",
        "compatibility_table": "Generated compatibility table data used in the listing",
        "ebay_vehicle_compatibility": "Generated eBay vehicle compatibility text for the listing",
        "amazon_vehicle_compatibility": "Generated Amazon vehicle compatibility text for the listing",
        "part_type": "General type or category of the part used in the listing",
        "part_terminology_id": "Standardized part terminology identifier",
        "part1": "Primary part identifier associated with this listing",
        "part1_quantity": "Quantity of part1 included in the listing",
        "part1_supplier_pn": "Supplier part number for part1",
        "part1_part_sku": "Internal SKU for part1",
        "part1_enabled": "Flag indicating if part1 is active and should be used in the listing",
        "part1_epid": "eBay Product ID for part1",
        "part1_asin": "Amazon ASIN for part1",
        "part1_upc": "UPC code for part1",
        "part1_brand_aaia_id": "Brand AAIA identifier for part1",
        "part1_subbrand_aaia_id": "Sub-brand AAIA identifier for part1",
        "part1_oem_mfg": "OEM manufacturer name for part1",
        "part1_oem_pn": "OEM part number for part1",
        "part1_aftermarket_mfg": "Aftermarket manufacturer name for part1",
        "part1_aftermarket_pn": "Aftermarket part number for part1",
        "part1_description": "Description of part1 used in the listing",
        "part1_part_type": "Specific part type or category for part1",
        "part1_attribute": "Attribute data describing features of part1",
        "part1_item_length_in": "Physical length of part1 in inches",
        "part1_item_width_in": "Physical width of part1 in inches",
        "part1_item_height_in": "Physical height of part1 in inches",
        "part1_item_weight_lbs": "Physical weight of part1 in pounds",
    },
}